# This is a basic workflow to help you get started with Actions

name: Check

# Controls when the action will run.
on:
    pull_request:

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    prepare:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup node
                uses: actions/setup-node@v2
                with:
                    node-version: '16'

            -   name: Cache node modules
                uses: actions/cache@v2
                env:
                    cache-name: cache-node-modules
                with:
                    path: |
                        node_modules
                    key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

            -   name: Install
                run: npm ci

    build:
        runs-on: ubuntu-latest

        needs:
            - prepare

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup node
                uses: actions/setup-node@v2
                with:
                    node-version: '16'

            -   name: Cache node modules
                uses: actions/cache@v2
                env:
                    cache-name: cache-node-modules
                with:
                    path: |
                        node_modules
                    key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

            -   name: Build packages
                run: CI=false npm run build

            -   name: Testing
                run: npm test
